### ISSUE TITLE
java 中set 方法 可否写几个注释呢，好多属性定义了两种类型

### ISSUE THREAD

**Issue by tianshaokai** [liangzhongtai/TipTextView#1]

**Comment by liangzhongtai** [comment]
大前天吃了些杏，胃中毒，等下注释就加上去。

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/40287758-2d5442d6-5ce2-11e8-84f5-5b7cc829128a.png)

我本来想实现这种效果，该库 能否实现动态创建呢，我上次尝试好像不行
